### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [gadgetmies/credit_card_midi#1]
Hello!

I found link to this project from https://www.hackster.io/news/this-clever-credit-card-sized-dj-console-aims-to-have-you-cutting-and-mixing-on-the-move-ce35b8ec55cd

Could you please add information about license of this repository — is it allowed to copy, change and use the code and board schematic files in any purpose?
It would be great to see any popular open source license.

**Comment by gadgetmies** [comment]
Hi! 

Thank you for opening this issue! I totally forgot to add a license earlier. I now added GPLv3 LICENSE file. Hope this works for you. If not, please let me know!
